name: Rust

on:
  push:
    branches:
      - main
      - version-*
  pull_request:
    branches:
      - main
      - version-*
  schedule:
    - cron:  '0 0 * * 0-6'

jobs:
  build:
    name: build (msrv)
    uses: ./.github/workflows/_build-rust.yml
    with:
      rust-version: 1.68.0
